### PR TITLE
Milestone-1

### PR DESCRIPTION
**Pull request by Arpit1204**
->Included Concepts:-

- `ERD` and `Schema`

- Loom [Link](https://www.loom.com/share/67980b6e8c954661bbcecb45e3787bb6?sid=d1933c48-8c22-4386-b177-70cc07e78915)

### CODE REVIEW

**Comment by PRASANNAPATHI** [comment]
1. 'Blood Type' entity should be renamed to 'Blood Details' or other common names to specify. And donar's blood type should be foreign key from Blood Type table. 

2. There shouldn't exist direct donation between donar and receiver, want to remove 'Blood Transfusion' entity, Every receiver should get blood from the 'Blood Bank', so make connection to Blood Bank from Receiver as maintained for 'Blood Donation',

**Comment by Arpit1204** [comment]
Hey @PRASANNAPATHI ,
Hope you are doing well, Can we have a small meet if possible, I want to understand your perspective regarding the 2nd point.

**Comment by PRASANNAPATHI** [comment]
update the diagrams, as discussed in meet.

**Comment by PRASANNAPATHI** [comment]
Yeah, now everything looks good.

You can merge it now.

**Pull request merged**
